import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/shared/components/Header";
import Footer from "@/shared/components/Footer";
import { ModalProvider } from "@/provider/ModalProvider";
import UserProvider from "@/provider/UserProvider";
import { EnrollmentsProvider } from "@/provider/EnrollmentsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider>
          <EnrollmentsProvider>
            <ModalProvider>
              <Header />
              <main className="flex-1 container">{children}</main>
              <Footer />
            </ModalProvider>
          </EnrollmentsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
