import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/shared/components/Header";
import Footer from "@/shared/components/Footer";
import { ModalProvider } from "@/provider/ModalProvider";
import UserProvider from "@/provider/UserProvider";
import { EnrollmentsProvider } from "@/provider/EnrollmentsProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // optional (for Tailwind)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <UserProvider>
          <EnrollmentsProvider>
            <ModalProvider>
              <Header />
              <main className="flex-1 container pb-40.25">{children}</main>
              <Footer />
            </ModalProvider>
          </EnrollmentsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
